version: '3'
services:
  application:
    container_name: app_test
    build:
      context: ./application
      dockerfile: Dockerfile.test
    command: 'python -m pytest -v -p no:cacheprovider -p no:warnings'
    volumes:
      - './application:/app'
    environment:
      - FLASK_ENV=development
      - MONGODB_HOST=mongodb
      - STORAGE_HOST=http://storage_server:1000
      - APP_CONFIG_FILE=config/testing.cfg
    depends_on: 
      - mongodb
      - storage_server
  authentication:
    container_name: auth_test
    build:
      context: ./authentication
      dockerfile: Dockerfile.test
    command: 'python -m pytest -v -p no:cacheprovider'
    volumes:
      - './authentication:/app'
    environment:
      - FLASK_ENV=development
      - MONGODB_HOST=mongodb
      - APP_CONFIG_FILE=config/testing.cfg
    depends_on: 
      - mongodb
    logging:
      driver: none
  storage_server:
    build:
      context: ./storage
      dockerfile: Dockerfile
    volumes:
      - './storage:/app'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server
      - STORAGE_PORT=1000
      - APP_CONFIG_FILE=config/development.cfg
    ports:
      - 1000:1000
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./test-data/db:/data/db
    command: mongod --smallfiles --quiet
    logging:
      driver: none