version: '3'
services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile.test
    command: 'python -m pytest -q -p no:cacheprovider'
    volumes:
      - './application:/app'
    environment:
      - FLASK_ENV=development
      - APP_CONFIG_FILE=config/testing.cfg
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile.test
    command: 'python -m pytest -q -p no:cacheprovider'
    volumes:
      - './authentication:/app'
    environment:
      - FLASK_ENV=development
      - APP_CONFIG_FILE=config/testing.cfg