version: '3'
services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - './application:/app'
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app_logic
      - FLASK_ENV=development
      - ZK_HOST=zookeeper
      - MONGODB_HOST=mongodb
      - STORAGE_HOST_0=storage_server_0
      - STORAGE_HOST_1=storage_server_1
      - APP_CONFIG_FILE=config/development.cfg
    depends_on:
      - zookeeper 
      - mongodb
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    volumes:
      - './authentication:/app'
    ports:
      - 5001:5001
    environment:
      - FLASK_APP=auth
      - FLASK_ENV=development
      - MONGODB_HOST=mongodb
      - APP_CONFIG_FILE=config/development.cfg
    depends_on: 
      - mongodb
  storage_server_0:
    build:
      context: ./storage
      dockerfile: Dockerfile
    volumes:
      - './storage:/app'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server
      - ZK_HOST=zookeeper
      - STORAGE_ID=0
      - APP_CONFIG_FILE=config/development.cfg
    ports:
      - 1000:1000
    depends_on:
      - zookeeper
  storage_server_1:
    build:
      context: ./storage
      dockerfile: Dockerfile
    volumes:
      - './storage:/app'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server
      - ZK_HOST=zookeeper
      - STORAGE_ID=1
      - APP_CONFIG_FILE=config/development.cfg
    ports:
      - 1001:1001
    depends_on:
      - zookeeper
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles #--quiet
    logging:
      driver: none
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
      - '2888'
      - '3888'
    volumes:
      - 'zookeeper_data_dev:/bitnami'
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
volumes:
  zookeeper_data_dev:
    driver: local