version: '3'
services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile.test
    command: 'python -m pytest -v -p no:cacheprovider'
    volumes:
      - './application:/app'
    environment:
      - FLASK_ENV=development
      - APP_CONFIG_FILE=config/testing.cfg
    depends_on: 
      - mongodb
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile.test
    command: 'python -m pytest -v -p no:cacheprovider'
    volumes:
      - './authentication:/app'
    environment:
      - FLASK_ENV=development
      - MONGODB_HOST=mongodb
      - APP_CONFIG_FILE=config/testing.cfg
    depends_on: 
      - mongodb
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./test-data/db:/data/db
    command: mongod --smallfiles --quiet