version: '3'
services:
  application:
    build:
      context: ./application
      dockerfile: Dockerfile
    volumes:
      - './application:/app'
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app_logic
      - FLASK_ENV=development
      - MONGODB_HOST=mongodb
      - STORAGE_HOST=http://storage_server:1000
      - APP_CONFIG_FILE=config/development.cfg
    depends_on: 
      - mongodb
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    volumes:
      - './authentication:/app'
    ports:
      - 5001:5001
    environment:
      - FLASK_APP=auth
      - FLASK_ENV=development
      - MONGODB_HOST=mongodb
      - APP_CONFIG_FILE=config/development.cfg
    depends_on: 
      - mongodb
  storage_server:
    build:
      context: ./storage
      dockerfile: Dockerfile
    volumes:
      - './storage:/app'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server
      - STORAGE_PORT=1000
      - APP_CONFIG_FILE=config/development.cfg
    ports:
      - 1000:1000
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles #--quiet